const filmsData = [
  {
    id: 1,
    image: require("../../img/onePiece.jpg"),
    title: "One Piece - Đảo Hải Tặc",
    year: "1999",
    nation: "Japan",
    Description: `Mùa thứ 2 của Jujutsu Kaisen nè!`,
  },
  {
    id: 2,
    image: require("../../img/blackClover.jpg"),
    title: "Black Clover (TV)",
    year: "2017",
    nation: "Japan",
    Description: `Mùa thứ 2 của Jujutsu Kaisen nè!`,
  },
  {
    id: 3,
    image: require("../../img/dietQuy.jpg"),
    title: "Thanh Gươm Diệt Quỷ",
    year: "2021",
    nation: "Japan",
    Description: `Mùa thứ 2 của Jujutsu Kaisen nè!`,
  },
  {
    id: 4,
    image: require("../../img/Conan.jpg"),
    title: "Thám Tử Lừng Danh Conan",
    year: "1996",
    nation: "Japan",
    Description: `Mùa thứ 2 của Jujutsu Kaisen nè!`,
  },
  {
    id: 5,
    image: require("../../img/bleach.jpg"),
    title: "Bleach",
    year: "2004",
    nation: "Japan",
    Description: `Mùa thứ 2 của Jujutsu Kaisen nè!`,
  },
  {
    id: 6,
    image: require("../../img/dauladailuc.jpg"),
    title: "Đấu La Đại Lục",
    year: "2018",
    nation: "China",
    Description: `Mùa thứ 2 của Jujutsu Kaisen nè!`,
  },
  {
    id: 7,
    image: require("../../img/chuthuatsu.jpg"),
    title: "Jujutsu Kaisen",
    year: "2020",
    nation: "Japan",
    Description: `Mùa thứ 2 của Jujutsu Kaisen nè!`,
  },
  {
    id: 8,
    image: require("../../img/naruto.jpg"),
    title: "Naruto: Sức Mạnh Vĩ Thú",
    year: "2007",
    nation: "Japan",
    Description: `Mùa thứ 2 của Jujutsu Kaisen nè!`,
  },
  {
    id: 9,
    image: require("../../img/hunterx.jpg"),
    title: "Hunter x Hunter, HxH ",
    year: "2011",
    nation: "Japan",
    Description: `Mùa thứ 2 của Jujutsu Kaisen nè!`,
  },
];

export default filmsData;
